language: python
sudo: false
python:
- 3.4
- 3.5
- 3.6
- 3.7-dev
- pypy
install:
- pip install .[test]
script:
- python setup.py test
after_success:
- coverage report -m
- pip install coveralls
- coveralls
deploy:
  provider: pypi
  user: thiagofigueiro
  password:
    secure: eTHCGo6yll/3MNlBDKpRX+aZx6zVE+/WC55xQcaOhUYEGn3hZbl41hEnr4fxLEalyA3GVWhu5QH7anLDLUDy1UFpFJ8G9DPqjF0Ac2GssQ0y0cH0tZ6vVH5zFMQpODbRoVCQu2gS6fSBTGFX3HfEC5Z1x3Pf5vLfkjOwIfS/dQNQljbPbdA96NG/c9kezAsqq4vQ/jzCAIO0CafRBcHralO8ko4ekWW4erma9wNeDIyeWWSKD0m/0LiVlm9s3TrpANs2Iz/o/VcvoCk4wAJ3KyWOJlcbT7BSg4jBtgQ8W71HSE28mGa69WusBgEkMnl8dE4PuKf6E1Sl66efT9l8vns+4pMij5+vpXbSQp9BlR9Dyg4NGZQzQ67DydTgUmySh+E00/WHoUSrAJIFZ1UgjOXRczw9qI1rNk7EnqbImLbZbFzM3j+wxQbSRDeuT38yBFQ7qL/ZT216vVAZqCRXmRK7Mn0F+NdJb0O/YQwXVfgf8TbQoiZaN52Ni3TmFz6QKtID51P81YBh3q+wnukxx/mrSdvza/l2A8Yd/0p2QDp9sOTvw9GSTcDCJAF2jxBm7e8EwTzGltYwKVepZUdNg+NnqaUrIteCxg0PYz4XaqCBWc0Jb8lIPZsXPV1M+aTE7i85c1NOLZKkh2BIX5RkvFRqAyj2+ATS2fxRf+jFRxg=
  on:
    condition: "$TRAVIS_PYTHON_VERSION == '3.6'"
    repo: thiagofigueiro/faker_web
    tags: true
  distributions: sdist bdist_wheel
